<a href="https://colab.research.google.com/github/AditiDalal108/Reco-Sys/blob/main/Recommender_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd

In [6]:
url = "https://grouplens.org/datasets/movielens/32m/"
!wget https://files.grouplens.org/datasets/movielens/ml-32m.zip
!unzip ml-32m.zip

ratings = pd.read_csv("ml-32m/ratings.csv")
movies = pd.read_csv("ml-32m/movies.csv")
tags = pd.read_csv("ml-32m/tags.csv")


print ("Ratings dataset shape :" , ratings.shape)

ratings.head()

--2026-04-06 15:42:50--  https://files.grouplens.org/datasets/movielens/ml-32m.zip
Resolving files.grouplens.org (files.grouplens.org)... 128.101.96.204
Connecting to files.grouplens.org (files.grouplens.org)|128.101.96.204|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 238950008 (228M) [application/zip]
Saving to: ‘ml-32m.zip.1’

ml-32m.zip.1        100%[===================>] 227.88M  27.4MB/s    in 7.8s

2026-04-06 15:42:58 (29.4 MB/s) - ‘ml-32m.zip.1’ saved [238950008/238950008]

Archive:  ml-32m.zip
replace ml-32m/tags.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace ml-32m/links.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace ml-32m/README.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace ml-32m/checksums.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace ml-32m/ratings.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace ml-32m/movies.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
Ratings dataset shape : (32000204, 4)

   userId  movieId  rating  timestamp
0       1       17     4.0  944249077
1       1       25     1.0  944250228
2       1       29     2.0  943230976
3       1       30     5.0  944249077
4       1       32     5.0  943228858

In [19]:
print ("Movies dataset shape :" , movies.shape)
movies.head()

Movies dataset shape : (87585, 3)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [20]:
print ("Tags dataset shape :" , tags.shape)
tags.head()

Tags dataset shape : (2000072, 4)

   userId  movieId          tag   timestamp
0      22    26479  Kevin Kline  1583038886
1      22    79592     misogyny  1581476297
2      22   247150   acrophobia  1622483469
3      34     2174        music  1249808064
4      34     2174        weird  1249808102

In [13]:
tags['movieId'].nunique()

51323

In [23]:
movies["year"] = movies["title"].str.extract(r"\((\d{4})\)")
movies["title"] = movies["title"].str.replace(r"\(\d{4}\)", "", regex=True).str.strip()
movies['genres'] = movies['genres'].str.split('|')
movies.head()

,movieId,title,genres,year
0,1,Toy Story,"[Adventure, Animation, Children, Comedy, Fantasy]",NaN
1,2,Jumanji,"[Adventure, Children, Fantasy]",NaN
2,3,Grumpier Old Men,"[Comedy, Romance]",NaN
3,4,Waiting to Exhale,"[Comedy, Drama, Romance]",NaN
4,5,Father of the Bride Part II,[Comedy],NaN